# Generated by Django 4.2.7 on 2024-01-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mypage.models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0005_remove_report_category_remove_report_char_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="useremail",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=mypage.models.get_file_path
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="report",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_report",
                to="report.report",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
