# Generated by Django 4.2.7 on 2024-01-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0005_remove_report_category_remove_report_char_count_and_more"),
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="report",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_report",
                to="report.report",
            ),
            preserve_default=False,
        ),
    ]
