# Generated by Django 4.2.7 on 2024-01-08 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0002_profile_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="report",
        ),
    ]
