# Generated by Django 4.2.7 on 2024-01-08 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0003_alter_profile_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
