# Generated by Django 4.2.7 on 2024-01-08 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mypage", "0003_remove_profile_address_remove_profile_intro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default=1, max_length=50, verbose_name="사용자_주소"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="intro",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default=1, max_length=20, verbose_name="사용자_전화번호"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="useremail",
            field=models.EmailField(default=1, max_length=128, verbose_name="사용자_이메일"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
