# Generated by Django 4.2 on 2023-12-28 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="isComplete",
        ),
    ]
