# Generated by Django 4.2.7 on 2024-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_question_image_alter_answer_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
