# Generated by Django 4.2 on 2023-12-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_remove_answer_user_remove_question_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
