# Generated by Django 4.2.7 on 2023-12-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_remove_question_postid_question_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="id",
        ),
        migrations.AddField(
            model_name="question",
            name="postId",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
