# Generated by Django 4.2 on 2024-01-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_user_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CATEGORY",
            fields=[
                ("cID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cName",
                    models.CharField(max_length=20, unique=True, verbose_name="카테고리명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="REPORT",
            fields=[
                ("reportID", models.AutoField(primary_key=True, serialize=False)),
                ("script", models.TextField()),
                ("questions", models.TextField()),
                ("answers", models.TextField()),
                ("voice_analysis", models.TextField()),
                ("attitude_analysis", models.TextField()),
                ("script_analysis", models.TextField()),
                ("total_analysis", models.TextField()),
                ("rDatetime", models.DateTimeField()),
                ("category", models.ManyToManyField(to="report.category")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
    ]
