# Generated by Django 4.2 on 2023-12-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "accounts",
            "0002_remove_user_body_remove_user_test_remove_user_uuid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CATEGORY",
            fields=[
                ("cID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cName",
                    models.CharField(max_length=20, unique=True, verbose_name="카테고리명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="REPORT",
            fields=[
                ("reportID", models.AutoField(primary_key=True, serialize=False)),
                ("script", models.TextField()),
                ("question1", models.TextField()),
                ("question2", models.TextField()),
                ("question3", models.TextField()),
                ("answer1", models.TextField()),
                ("answer2", models.TextField()),
                ("answer3", models.TextField()),
                ("va", models.TextField()),
                ("aa", models.TextField()),
                ("strength", models.TextField()),
                ("weakness", models.TextField()),
                ("suppliment", models.TextField()),
                ("rDatetime", models.DateTimeField()),
                ("category", models.ManyToManyField(to="report.category")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
    ]
