# Generated by Django 4.2 on 2024-01-02 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_alter_report_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="category",
        ),
        migrations.AddField(
            model_name="report",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.category",
            ),
        ),
    ]
