# Generated by Django 4.2 on 2024-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0003_remove_report_category_report_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="char_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="empty_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="face_recog",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="filler_word",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="staic",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="total_time",
            field=models.IntegerField(default=0),
        ),
    ]
