# Generated by Django 4.2 on 2024-01-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0004_report_char_count_report_empty_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="category",
        ),
        migrations.RemoveField(
            model_name="report",
            name="char_count",
        ),
        migrations.RemoveField(
            model_name="report",
            name="empty_count",
        ),
        migrations.RemoveField(
            model_name="report",
            name="face_recog",
        ),
        migrations.RemoveField(
            model_name="report",
            name="filler_word",
        ),
        migrations.RemoveField(
            model_name="report",
            name="script",
        ),
        migrations.RemoveField(
            model_name="report",
            name="staic",
        ),
        migrations.RemoveField(
            model_name="report",
            name="total_time",
        ),
        migrations.AddField(
            model_name="report",
            name="face_recog_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="gap_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="speed_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="static_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="surplus_rate",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="CATEGORY",
        ),
    ]
